export const MOCK_EVENTS = [
    {
        id: "evt-1",
        title: "Summer Music Festival 2026",
        description: "Join us for the biggest music festival of the summer! Featuring top artists from around the world across three stages.",
        date: "2026-07-15T12:00:00Z",
        end_date: "2026-07-17T23:00:00Z",
        venue: "Central Park",
        city: "London",
        category: "music",
        image_url: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200",
        price_from: 45.0,
        status: "live",
        featured: true,
        organizer_id: "org-1",
    },
    {
        id: "evt-2",
        title: "Late Night Comedy Club",
        description: "A night of hilarious stand-up comedy with local and international comedians.",
        date: "2026-04-10T20:00:00Z",
        venue: "The Laugh Factory",
        city: "Manchester",
        category: "comedy",
        image_url: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=1200",
        price_from: 15.0,
        status: "live",
        featured: true,
        organizer_id: "org-2",
    },
    {
        id: "evt-3",
        title: "Tech Innovation Summit",
        description: "Explore the latest in AI, blockchain, and sustainable tech with world-class speakers.",
        date: "2026-05-22T09:00:00Z",
        venue: "Convention Centre",
        city: "Birmingham",
        category: "business",
        image_url: "https://images.unsplash.com/photo-1540575861501-7c91211c889d?w=1200",
        price_from: 150.0,
        status: "live",
        organizer_id: "org-3",
    },
    {
        id: "evt-4",
        title: "Gourmet Food & Wine Expo",
        description: "Taste the finest wines and artisanal foods from local producers.",
        date: "2026-06-05T11:00:00Z",
        venue: "Old Docklands",
        city: "Liverpool",
        category: "food_drink",
        image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1200",
        price_from: 25.0,
        status: "live",
        organizer_id: "org-1",
    },
    {
        id: "evt-5",
        title: "Urban Art Showcase",
        description: "A vibrant exhibition of street art and contemporary installations.",
        date: "2026-04-20T10:00:00Z",
        venue: "Warehouse Gallery",
        city: "Bristol",
        category: "arts",
        image_url: "https://images.unsplash.com/photo-1460661419201-fd4ce186860d?w=1200",
        price_from: 0,
        status: "live",
        organizer_id: "org-2",
    },
    {
        id: "evt-6",
        title: "Zen Yoga Workshop",
        description: "Find your inner peace with a full day of guided yoga and meditation.",
        date: "2026-04-15T08:00:00Z",
        venue: "Peaceful Studio",
        city: "London",
        category: "wellness",
        image_url: "https://images.unsplash.com/photo-1545208393-2169299770a4?w=1200",
        price_from: 35.0,
        status: "live",
        organizer_id: "org-3",
    },
];

export const MOCK_BOOKINGS = [
    {
        id: "bk-1",
        booking_ref: "EVT-ABC123",
        event_id: "evt-1",
        attendee_name: "John Doe",
        attendee_email: "john@example.com",
        total_qty: 2,
        total_paid: 90.0,
        scanned: false,
        status: "confirmed",
        created_at: "2026-03-01T10:00:00Z",
        ticket_items: [{ label: "General Admission", qty: 2 }]
    },
];

export const MOCK_PROMO_CODES = [
    { id: "pc-1", code: "EARLYBIRD", discount_pct: 20, active: true },
    { id: "pc-2", code: "WELCOME", discount_amt: 5, active: true },
];

export const MOCK_ORG_PROFILE = {
    id: "org-1",
    business_name: "London Events Co.",
    description: "Creating unforgettable experiences across the UK since 2018.",
    logo_url: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=200",
    contact_email: "hello@londonevents.co",
    website: "https://londonevents.co",
};
